# fly.toml app configuration file generated for monitoring-demo-wispy-frog-9958 on 2024-12-02T22:01:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monitoring-demo-wispy-frog-9958'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 3000
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 9090
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 4317
    handlers = ['tls']

  [[services.ports]]
    port = 3200
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 11211
    handlers = ['tls']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 8000
  path = '/metrics'
  https = false
