global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    params:
      format: [prometheus]
    static_configs:
      - targets: ['app:8000']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
  
rule_files:
  - alerts.yml